permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

cover: /assets/images/default-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Capecchi Family Recipes
title: CFR
description: "Sharing Love Through Good Food"
keywords: ""
url: #http://nandomoreira.me
baseurl: ""
#baseurl: "/mug"
domain_name: capecchifamilyrecipes.com
# google_analytics: UA-52446115-1
repo: #http://github.com/nandomoreirame/mug
disqus_shortname: #"nandothemes"

author:
  name      : Bill Capecchi
  image     : /assets/images/author.jpg
  email     : william.capecchi@gmail.com
  url       : #http://nandomoreira.me
  facebook  : #http://facebook.com/fernando.dev
  twitter   : #http://twitter.com/nandomoreirame
  instagram : #http://instagram.com/nandomoreira.me
  github    : #http://github.com/nandomoreirame
  linkedin  : #http://linkedin.com/in/nandomoreirame
  bio       : #"Desenvolvedor Front-end/Wordpress entusiasta de performance, design responsivo e usabilidade, sempre em busca do melhor projeto e de um bom caf√©."

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
